# TweetPoo.R
# Author:     John R. Brandon, PhD
# Purpose:    Tweet water quality data (coliform levels) from SF Water Power
#             Sewer website
# Notes:      ScrapeWebData.R does the heavy lifting. See the comments in that
#             file for more details re: scraping, logging etc.

# install.packages("twitteR")
library("twitteR")

rm(list = ls())     # Clear workspace
print(Sys.time())   # Check
print(getwd())

# Run code in ScrapeWebData.R file
# The Bash rShellScript.sh starts in ./BeachWater directory (e.g. ~/BeachWater)
# The R source codes (and Bash script) are under ./BeachWater/R
source("./R/ScrapeWebData.R")

# If previously logged date is not equal to most recent date, continue processing
# Comparative dates initialized by ScrapeWebData.R code
if(ymd_sample_date != ymd(LastDate)){

  # Credentials ------------------------------------------------------------------
  # Consumer Key (API Key)	wOGaeEQzlUbYZW2iagxgY8IOH
  api_key = "wOGaeEQzlUbYZW2iagxgY8IOH"

  # Consumer Secret (API Secret)	hnIHppfM1mvbHqs8S1UnaeZU0OFHI7F2xVwGYOe8hGBRnIApG6
  api_secret = "hnIHppfM1mvbHqs8S1UnaeZU0OFHI7F2xVwGYOe8hGBRnIApG6"

  # Access Token	710199368561860608-7PSV44DgI7Io4rgd3cbcis9ykRMVUbz
  access_token = "710199368561860608-7PSV44DgI7Io4rgd3cbcis9ykRMVUbz"

  # Access Token Secret	ctrg9lKQ3dxqfFSdlnNqeybZqjQy3GZd2dhf9C7jKKaMU
  access_secret = "ctrg9lKQ3dxqfFSdlnNqeybZqjQy3GZd2dhf9C7jKKaMU"

  # Set up OAuth credentials for a twitteR session -------------------------------
  setup_twitter_oauth(consumer_key = api_key,
                      consumer_secret = api_secret,
                      access_token = access_token,
                      access_secret = access_secret)

  tweet(tweet_text) # Tweet text generated by ScrapeWebData.R code

  # Beach Poo Bot's first tweet as example -------------------------------------
  # tweet(text = "Hello World")
  # tweet(text = "Time series plot", mediaPath = "timeseries.png")  # Attach plot

}

