# TweetShit.R
# Author:     John R. Brandon, PhD
# Purpose:    Tweet water quality data (coliform levels) from SF Water Power
#             Sewer website
# Notes:      ScrapePoo.R does the heavy lifting. See the comments in that
#             file for more details re: scraping, logging etc.
#
# Copyright 2016 John R. Brandon
# This program is distributed under the terms of the GNU General Public License v3
# (provided in the ../LICENSE file).

# install.packages("twitteR")
library("twitteR")  # R interface with Twitter API

rm(list = ls())     # Clear workspace
print(Sys.time())   # Written to stdout log file as a check.

# Run code in ScrapeWebData.R file
# The Bash rShellScript.sh starts in ./BeachWater directory (e.g. ~/BeachWater)
# The R source codes (and Bash script) are under ./BeachWater/R
source("./R/ScrapePoo.R")
source("./R/GetBeachStatus.R")

# Credentials ------------------------------------------------------------------
# Consumer Key (API Key)	wOGaeEQzlUbYZW2iagxgY8IOH
api_key = "wOGaeEQzlUbYZW2iagxgY8IOH"

# Consumer Secret (API Secret)	hnIHppfM1mvbHqs8S1UnaeZU0OFHI7F2xVwGYOe8hGBRnIApG6
api_secret = "hnIHppfM1mvbHqs8S1UnaeZU0OFHI7F2xVwGYOe8hGBRnIApG6"

# Access Token	710199368561860608-7PSV44DgI7Io4rgd3cbcis9ykRMVUbz
access_token = "710199368561860608-7PSV44DgI7Io4rgd3cbcis9ykRMVUbz"

# Access Token Secret	ctrg9lKQ3dxqfFSdlnNqeybZqjQy3GZd2dhf9C7jKKaMU
access_secret = "ctrg9lKQ3dxqfFSdlnNqeybZqjQy3GZd2dhf9C7jKKaMU"

# Set up OAuth credentials for a twitteR session -------------------------------
setup_twitter_oauth(consumer_key = api_key,
                    consumer_secret = api_secret,
                    access_token = access_token,
                    access_secret = access_secret)

# If previously logged date is not equal to most recent date, tweet new levels and status list.
# Comparative dates initialized by ScrapeWebData.R code
sample_updated = ymd_sample_date != ymd(LastDate)
if(sample_updated){
  tweet(tweet_text)    # Tweet text generated by ScrapePoo.R code
  tweet(status_tweet)  # Tweet status of sampling locations ("Open" or "Posted")
  # Beach Poo Bot's first tweet as example -------------------------------------
  # tweet(text = "Hello World")
  # tweet(text = "Time series plot", mediaPath = "timeseries.png")  # Attach plot
}

# The condition above re: updated counts is currently only enforced for Ocean Beach at Lincoln Way
# If the status of ANY of the beaches on file (eg Sloat or Chrissie Field) has changed,
# want to send a tweet with the status list, but not the tweet with counts at Lincoln (which are old)
if(status_tweet != "No status update" & sample_updated == FALSE){
  tweet(status_tweet)
}

