# TweetShit.R
# Author:     John R. Brandon, PhD
# Purpose:    Tweet water quality data (coliform levels) from SF Water Power
#             Sewer website
# Notes:      ScrapePoo.R does the heavy lifting. See the comments in that
#             file for more details re: scraping, logging etc.
#
# Copyright 2016 John R. Brandon
# This program is distributed under the terms of the GNU General Public License v3
# (provided in the ../LICENSE file).

# install.packages("twitteR")
library("twitteR")  # R interface with Twitter API

rm(list = ls())     # Clear workspace
print(Sys.time())   # Written to stdout log file as a check.

# Run code in ScrapeWebData.R file
# The Bash rShellScript.sh starts in ./BeachWater directory (e.g. ~/BeachWater)
# The R source codes (and Bash script) are under ./BeachWater/R
source("./R/ScrapePoo.R")
source("./R/GetBeachStatus.R")

# Credentials ------------------------------------------------------------------
# Consumer Key (API Key)
api_key = "Your Consumer Key Here"

# Consumer Secret (API Secret)
api_secret = "Your Consumer Secret Here"

# Access Token
access_token = "Your Access Token Here"

# Access Token Secret
access_secret = "Your Access Token Secret Here"

# Set up OAuth credentials for a twitteR session -------------------------------
setup_twitter_oauth(consumer_key = api_key,
                    consumer_secret = api_secret,
                    access_token = access_token,
                    access_secret = access_secret)

# Comparative dates initialized by ScrapeWebData.R code
sample_updated = ymd_sample_date != ymd(LastDate)

if(sample_updated){
  # If previously logged date is not equal to most recent date, tweet new levels and status list.
  tweet(tweet_text)    # Tweet text generated by ScrapePoo.R code
  for(ii in seq_along(status_tweet)){
    tweet(status_tweet[ii]) # Tweet status of sampling locations ("Open" or "Posted")
  }
  # Beach Poo Bot's first tweet as example -------------------------------------
  # tweet(text = "Hello World")
  # tweet(text = "Time series plot", mediaPath = "timeseries.png")  # Attach plot
}

# The condition above re: updated counts is currently only enforced for Ocean Beach at Lincoln Way
# If the status of ANY of the beaches on file (eg Sloat or Chrissie Field) has changed,
# want to send a tweet with the status list, but not the tweet with counts at Lincoln (which are old)
if(status_tweet != "The latest sample has not changed the posting status at Lincoln Way." & sample_updated == FALSE){
  for(ii in seq_along(status_tweet)){
    tweet(status_tweet[ii])
  }
}
